<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#050706"><title>Login Billing · FIKSUM</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        :root{color-scheme:dark;--green:#b8f36b;--muted:#9ba7a0;--line:#202622}html,body{min-height:100%;background:#050706;color:#f3f7f3}body{background-image:radial-gradient(ellipse at 18% 10%,rgba(105,178,93,.13),transparent 32rem),radial-gradient(ellipse at 100% 85%,rgba(38,128,106,.1),transparent 28rem)}.login-wrap{min-height:100vh;display:grid;grid-template-columns:minmax(0,1fr) minmax(380px,520px);max-width:1240px;margin:auto;padding:clamp(1rem,4vw,3.5rem);gap:clamp(2rem,7vw,7rem);align-items:center}.brand-lockup{display:flex;align-items:center;gap:.8rem;color:#fff;text-decoration:none}.brand-mark{display:grid;place-items:center;width:44px;height:44px;border-radius:14px;background:var(--green);color:#10170d;font-size:1.2rem;font-weight:900}.brand-title{font-size:1rem;font-weight:760}.brand-subtitle{color:var(--muted);font-size:.7rem;letter-spacing:.15em;text-transform:uppercase}.intro{padding-bottom:1rem}.intro h1{max-width:600px;margin:2rem 0 1rem;font-size:clamp(2.3rem,5.4vw,4.5rem);line-height:1.04;letter-spacing:-.06em;font-weight:780}.intro h1 span{color:var(--green)}.intro p{max-width:510px;color:#aab4ad;font-size:1.05rem;line-height:1.7}.feature{display:flex;align-items:center;gap:.7rem;color:#b8c2ba;font-size:.85rem;margin-top:1.5rem}.feature i{width:8px;height:8px;border-radius:50%;background:var(--green);box-shadow:0 0 14px var(--green)}.login-card{border:1px solid var(--line);border-radius:22px;background:linear-gradient(145deg,rgba(17,21,18,.98),rgba(10,12,11,.98));box-shadow:0 28px 90px rgba(0,0,0,.45)}.login-card-body{padding:clamp(1.4rem,4vw,2.2rem)}.login-card h2{font-size:1.45rem;font-weight:730;letter-spacing:-.03em}.hint{color:var(--muted);font-size:.86rem}.form-label{color:#e1e8e2;font-size:.84rem;font-weight:600}.form-control{min-height:49px;border:1px solid #303832;border-radius:11px;background:#090c0a;color:#fff}.form-control:focus{border-color:#8bc15a;box-shadow:0 0 0 .2rem rgba(184,243,107,.12);background:#0b0f0c;color:#fff}.form-control::placeholder{color:#778178}.btn-login{min-height:50px;border:0;border-radius:11px;background:var(--green);color:#10170d;font-weight:750}.btn-login:hover{background:#c8fa83;color:#10170d}.divider{display:flex;align-items:center;gap:.8rem;color:#707a72;font-size:.75rem}.divider:before,.divider:after{content:"";height:1px;background:#252c27;flex:1}.btn-portal{min-height:46px;border:1px solid #374039;border-radius:11px;color:#e3ebe4;background:#101411}.btn-portal:hover{border-color:var(--green);color:var(--green);background:#121811}.secure-note{color:#818d84;font-size:.75rem;text-align:center;margin-top:1rem}
        @media(max-width:800px){.login-wrap{grid-template-columns:1fr;max-width:560px;gap:1.8rem}.intro h1{font-size:clamp(2rem,9vw,3.2rem);margin:1.4rem 0 .8rem}.intro p{font-size:.93rem}.feature{display:none}}
    </style>
</head>
<body><main class="login-wrap">
    <section class="intro"><a class="brand-lockup" href="{{ route('login') }}"><span class="brand-mark">F</span><span><span class="brand-title d-block">FIKSUM</span><span class="brand-subtitle d-block">Internet Billing</span></span></a><h1>Kelola jaringan dan pelanggan <span>lebih mudah.</span></h1><p>Billing terintegrasi untuk mengatur layanan, tagihan, pembayaran, dan operasional jaringan internet Anda.</p><div class="feature"><i></i> Dashboard operasional dalam satu tempat</div></section>
    <section class="login-card"><div class="login-card-body"><div class="mb-4"><h2 class="mb-1">Masuk ke Billing</h2><p class="hint mb-0">Gunakan akun administrator atau staf Anda.</p></div>
        @if(session('error'))<div class="alert alert-danger">{{session('error')}}</div>@endif
        <form method="POST" action="{{route('login.attempt')}}">@csrf<div class="mb-3"><label class="form-label" for="email">Email</label><input id="email" name="email" type="email" class="form-control" placeholder="nama@contoh.com" value="{{old('email')}}" autocomplete="username" required></div><div class="mb-4"><label class="form-label" for="password">Password</label><input id="password" name="password" type="password" class="form-control" placeholder="Masukkan password" autocomplete="current-password" required></div><button class="btn-login w-100">Masuk ke Dashboard <span aria-hidden="true">→</span></button></form>
        <div class="divider my-4">atau</div><a href="{{route('portal.login')}}" class="btn-portal w-100 d-flex justify-content-center align-items-center text-decoration-none">Portal pelanggan</a><div class="secure-note">Akses aman · FIKSUM Internet Billing</div>
    </div></section>
</main></body>
</html>

