<?php
namespace App\Services;
use App\Models\Customer; use App\Models\FupState; use Illuminate\Support\Facades\DB; use Illuminate\Support\Carbon;
class FupService {
  public function __construct(private RouterOsService $routerOs){}
  public function collect():int{$count=0;$period=now(config('billing.timezone'))->format('Y-m');$activeMaps=[]; Customer::with(['router','package'])->where('status','active')->where('service_type','pppoe')->where('fup_enabled',true)->whereNotNull('pppoe_username')->whereNotNull('router_id')->chunkById(50,function($customers)use($period,&$count,&$activeMaps){$byRouter=[];foreach($customers as $c){$byRouter[$c->router_id]['router']=$c->router;$byRouter[$c->router_id]['customers'][]=$c;}foreach($byRouter as $routerId=>$bundle){try{if(!array_key_exists($routerId,$activeMaps))$activeMaps[$routerId]=$this->routerOs->activePppMap($bundle['router']);$map=$activeMaps[$routerId];foreach($bundle['customers'] as $customer){$row=$map[$customer->pppoe_username]??null;if(!$row)continue;$rx=(int)($row['bytes-in']??0);$tx=(int)($row['bytes-out']??0);$limit=(int)($customer->fup_limit_bytes?:optional($customer->package)->fup_limit_bytes?:0);$state=FupState::firstOrCreate(['customer_id'=>$customer->id,'period'=>$period]);$delta=0;if($state->last_sampled_at){$delta=($rx >= $state->last_rx ? $rx-$state->last_rx : $rx)+($tx >= $state->last_tx ? $tx-$state->last_tx : $tx);} $newTotal=$state->total_bytes+$delta;$state->update(['last_rx'=>$rx,'last_tx'=>$tx,'total_bytes'=>$newTotal,'last_sampled_at'=>now()]);DB::table('fup_samples')->insert(['customer_id'=>$customer->id,'period'=>$period,'rx_bytes'=>$rx,'tx_bytes'=>$tx,'delta_bytes'=>$delta,'total_bytes_after'=>$newTotal,'sampled_at'=>now(),'created_at'=>now(),'updated_at'=>now()]);$count++; if($limit>0 && $newTotal >= $limit && !$state->limited){$speed=$customer->fup_speed_after?:optional($customer->package)->fup_speed_after;if($speed){$normal=$customer->pppoe_profile_normal?:optional($customer->package)->normal_profile;$this->routerOs->setPppProfile($bundle['router'],$customer->pppoe_username,$speed);$this->routerOs->disconnectPppActive($bundle['router'],$customer->pppoe_username);$state->update(['limited'=>true]);DB::table('fup_logs')->insert(['customer_id'=>$customer->id,'period'=>$period,'action'=>'limited','total_bytes'=>$newTotal,'profile_before'=>$normal,'profile_after'=>$speed,'details'=>'FUP limit reached','created_at'=>now(),'updated_at'=>now()]);}}}}catch(\Throwable $e){report($e);}}});return $count;}
  public function resetMonthly():int{$period=now(config('billing.timezone'))->format('Y-m');$affected=0;FupState::with('customer.router','customer.package')->where('period','!=',$period)->where(function($q){$q->where('limited',true)->orWhere('total_bytes','>',0);})->chunkById(100,function($states)use(&$affected){foreach($states as $state){$customer=$state->customer;if($state->limited&&$customer){try{$this->restoreNormalProfile($customer);DB::table('fup_logs')->insert(['customer_id'=>$customer->id,'period'=>$state->period,'action'=>'reset','total_bytes'=>$state->total_bytes,'profile_before'=>$customer->fup_speed_after?:optional($customer->package)->fup_speed_after,'profile_after'=>$customer->pppoe_profile_normal?:optional($customer->package)->normal_profile,'details'=>'Monthly FUP reset','created_at'=>now(),'updated_at'=>now()]);}catch(\\Throwable $e){report($e);continue;}}$state->update(['total_bytes'=>0,'last_rx'=>0,'last_tx'=>0,'limited'=>false]);$affected++;}});return $affected;}
  private function restoreNormalProfile(Customer $customer):void{if(!$customer->router||!$customer->pppoe_username)return;$this->routerOs->setPppProfile($customer->router,$customer->pppoe_username,$customer->pppoe_profile_normal?:optional($customer->package)->normal_profile);$this->routerOs->disconnectPppActive($customer->router,$customer->pppoe_username);}
}
