<?php
namespace App\Services;
use App\Models\Customer; use Illuminate\Support\Facades\DB; use RuntimeException;
class IsolationService {
  public function __construct(private RouterOsService $routerOs){}
  public function isolate(Customer $customer):void{if(!$customer->router)return;if($customer->service_type==='pppoe'&&$customer->pppoe_username){$method=config('billing.isolation_method');if($method==='disable')$this->routerOs->enablePppSecret($customer->router,$customer->pppoe_username,false);else{$profile=$customer->pppoe_profile_isolir?:config('billing.isolation_profile');$this->routerOs->setPppProfile($customer->router,$customer->pppoe_username,$profile);}$this->routerOs->disconnectPppActive($customer->router,$customer->pppoe_username);}elseif($customer->service_type==='hotspot'&&$customer->hotspot_username){$this->routerOs->setHotspotUserEnabled($customer->router,$customer->hotspot_username,false);$this->routerOs->disconnectHotspotActive($customer->router,$customer->hotspot_username);}else{return;}DB::transaction(fn()=> $customer->update(['status'=>'isolated'])); }
  public function unisolate(Customer $customer):void{if(!$customer->router)return;if($customer->service_type==='pppoe'&&$customer->pppoe_username){$profile=$customer->pppoe_profile_normal ?: optional($customer->package)->normal_profile;if(!$profile)throw new RuntimeException('Profile normal belum diatur.');if(config('billing.isolation_method')==='profile')$this->routerOs->setPppProfile($customer->router,$customer->pppoe_username,$profile);$this->routerOs->enablePppSecret($customer->router,$customer->pppoe_username,true);}elseif($customer->service_type==='hotspot'&&$customer->hotspot_username){$this->routerOs->setHotspotUserEnabled($customer->router,$customer->hotspot_username,true);}else{return;}$customer->update(['status'=>'active']); }
  public function restoreNormalProfile(Customer $customer):void{ if($customer->service_type!=='pppoe'||!$customer->router||!$customer->pppoe_username)return; $profile=$customer->pppoe_profile_normal?:optional($customer->package)->normal_profile; if($profile)$this->routerOs->setPppProfile($customer->router,$customer->pppoe_username,$profile); }
}
