<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#050706">
    <title>Pendaftaran diterima · FIKSUM</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        :root{color-scheme:dark;--bg:#050706;--panel:#0d100f;--line:#202622;--muted:#9ba7a0;--green:#b8f36b}html,body{min-height:100%;background:var(--bg);color:#f3f7f3}body{background-image:radial-gradient(ellipse at 50% 0%,rgba(105,178,93,.13),transparent 34rem)}.topbar{border-bottom:1px solid rgba(255,255,255,.08);background:rgba(5,7,6,.78)}.brand-mark{display:grid;place-items:center;width:38px;height:38px;border-radius:12px;background:var(--green);color:#10170d;font-weight:900}.brand-name{font-weight:750}.brand-sub{font-size:.68rem;color:var(--muted);letter-spacing:.16em;text-transform:uppercase}.success-card{max-width:680px;border:1px solid var(--line);border-radius:22px;background:linear-gradient(145deg,#111512,#0a0d0b);box-shadow:0 24px 80px rgba(0,0,0,.4)}.success-mark{width:58px;height:58px;border:1px solid #55713e;border-radius:18px;background:rgba(184,243,107,.1);color:var(--green);display:grid;place-items:center;font-size:1.7rem}.eyebrow{color:#cce9b4;font-size:.75rem;letter-spacing:.1em;text-transform:uppercase}.muted{color:var(--muted)}.status-box{border:1px solid #514627;background:rgba(208,164,54,.08);border-radius:13px;padding:1rem;color:#d4c493;font-size:.86rem;line-height:1.6}.credential{border:1px solid #2a332d;border-radius:12px;background:#080b09;padding:.9rem}.credential label{color:var(--muted);font-size:.75rem;margin-bottom:.4rem}.credential .form-control{background:#050706;border-color:#303832;color:#f4f7f4;font-family:ui-monospace,monospace}.btn-copy{border:1px solid #3a463c;color:#e4ece5;background:#151a16}.btn-copy:hover{border-color:var(--green);color:var(--green)}.btn-main{min-height:50px;border:0;border-radius:11px;background:var(--green);color:#10170d;font-weight:750}.btn-main:hover{background:#c8fa83;color:#10170d}.pill{display:inline-flex;border:1px solid #334030;border-radius:999px;background:#101710;color:#c9e7ae;padding:.35rem .7rem;font-size:.75rem}
        @media(max-width:575px){.success-card{border-radius:17px}.success-body{padding:1.25rem!important}}
    </style>
</head>
<body>
<nav class="topbar"><div class="container py-3"><a class="d-inline-flex align-items-center gap-2 text-decoration-none text-light" href="{{ route('portal.login') }}"><span class="brand-mark">F</span><span><span class="brand-name d-block">FIKSUM</span><span class="brand-sub d-block">Internet Billing</span></span></a></div></nav>
<main class="container py-4 py-md-5"><div class="success-card mx-auto"><div class="success-body p-4 p-md-5">
    <div class="success-mark mb-3" aria-hidden="true">✓</div><div class="eyebrow mb-2">Permohonan berhasil dikirim</div><h1 class="h2 fw-bold mb-2">Terima kasih, {{ $customer->name }}.</h1><p class="muted mb-4">Pendaftaran Anda sudah tercatat. Tim FIKSUM akan menghubungi WhatsApp <strong class="text-light">{{ $customer->whatsapp_number }}</strong> untuk memeriksa area dan jadwal pemasangan.</p>
    <div class="status-box mb-4"><span class="pill mb-2">Menunggu verifikasi</span><br>Akun belum aktif dan belum ada konfigurasi MikroTik yang dibuat. Koneksi akan disiapkan setelah area terjangkau dan pemasangan dikonfirmasi.</div>
    <div class="d-flex justify-content-between align-items-end gap-2 mb-2"><div><h2 class="h5 fw-bold mb-1">Akses Portal Pelanggan</h2><p class="muted small mb-0">Simpan ID dan password berikut. Password hanya ditampilkan sekarang.</p></div></div>
    <div class="credential mb-2"><label for="customer_code">ID pelanggan</label><div class="input-group"><input id="customer_code" class="form-control" value="{{ $customer->customer_code }}" readonly><button class="btn btn-copy" type="button" data-copy="customer_code">Salin</button></div></div>
    <div class="credential mb-3"><label for="portal_password">Password portal</label><div class="input-group"><input id="portal_password" class="form-control" value="{{ $portalPassword }}" readonly><button class="btn btn-copy" type="button" data-copy="portal_password">Salin</button></div></div>
    <div class="d-flex justify-content-between align-items-center gap-3 border-top border-secondary pt-3 mb-4"><span class="muted small">Paket yang diajukan</span><span class="text-end fw-semibold">{{ $customer->package?->name ?? '—' }}<br><span class="muted small">Rp {{ number_format($customer->package?->price ?? 0,0,',','.') }}/bulan</span></span></div>
    <a class="btn btn-main w-100 d-flex align-items-center justify-content-center" href="{{ route('portal.login') }}">Masuk ke Portal Pelanggan <span class="ms-2" aria-hidden="true">→</span></a>
</div></div></main>
<script>document.querySelectorAll('[data-copy]').forEach(button=>button.addEventListener('click',async()=>{const input=document.getElementById(button.dataset.copy);try{await navigator.clipboard.writeText(input.value);button.textContent='Tersalin ✓'}catch{input.select();document.execCommand('copy');button.textContent='Tersalin ✓'}setTimeout(()=>button.textContent='Salin',1800)}));</script>
</body>
</html>

