@extends('layouts.app')
@section('content')
<h1 class="mb-4">Dashboard</h1>
<div class="row g-3">
    @foreach([['Total pelanggan',$stats['customers']],['Pelanggan aktif',$stats['active']],['Pelanggan isolir',$stats['isolated']],['Invoice bulan ini',$stats['invoice_month']],['Belum bayar',$stats['unpaid']],['Router online',$stats['routers_online'].' / '.$stats['routers']]] as $stat)
        <div class="col-sm-6 col-xl-2"><div class="card h-100"><div class="card-body"><div class="text-muted">{{ $stat[0] }}</div><div class="fs-4 fw-bold">{{ $stat[1] }}</div></div></div></div>
    @endforeach
</div>
<div class="card mt-4"><div class="card-body"><div class="d-flex flex-wrap align-items-center justify-content-between gap-2"><div><h2 class="h5 mb-1">Trafik MikroTik</h2><div class="small text-muted">Baca langsung dari interface pilihan tiap router; otomatis diperbarui setiap 30 detik. Siklus FUP tanggal 10–9; periode aktif {{ $fupCycle }}.</div></div><div class="d-flex align-items-center gap-2"><label class="small" for="traffic-router">Router</label><select id="traffic-router" class="form-select form-select-sm" style="width:auto"></select><span id="traffic-updated" class="small text-muted">Menunggu data…</span></div></div><div class="row g-3 my-2"><div class="col-sm-6"><div class="text-muted small">Download / RX</div><div id="traffic-rx" class="fs-4 fw-bold">—</div></div><div class="col-sm-6"><div class="text-muted small">Upload / TX</div><div id="traffic-tx" class="fs-4 fw-bold">—</div></div></div><div class="w-100" style="height:240px"><svg id="traffic-chart" viewBox="0 0 900 240" role="img" aria-label="Grafik trafik MikroTik download dan upload" style="width:100%;height:100%;overflow:visible"><path d="M48 12V200H888" fill="none" stroke="#555"/><path id="traffic-rx-line" fill="none" stroke="#32a6ff" stroke-width="3"/><path id="traffic-tx-line" fill="none" stroke="#f6b73c" stroke-width="3"/><text id="traffic-scale" x="8" y="18" fill="#adb5bd" font-size="12">Mbps</text></svg></div><div class="d-flex gap-3 small mt-2"><span style="color:#32a6ff">● Download</span><span style="color:#f6b73c">● Upload</span><span id="traffic-status" class="text-muted ms-auto"></span></div><div class="small text-muted mt-2">Grafik menyimpan hingga 30 sampel di browser selama halaman Dashboard terbuka. Isi nama interface WAN pada pengaturan router.</div></div></div>
@if(in_array($billingUser?->role,['super_admin','admin','finance'],true))
    <div class="row g-3 mt-1"><div class="col-md-4"><div class="card h-100"><div class="card-body"><div class="text-muted">Pendapatan bulan ini</div><div class="fs-4 fw-bold">Rp {{number_format($stats['paid_month'],0,',','.')}}</div></div></div></div><div class="col-md-4"><div class="card h-100"><div class="card-body"><div class="text-muted">Tagihan belum lunas</div><div class="fs-4 fw-bold">Rp {{number_format($stats['unpaid_amount'],0,',','.')}}</div></div></div></div><div class="col-md-4"><div class="card h-100"><div class="card-body"><div class="text-muted">Tripay hari ini</div><div class="fs-4 fw-bold">Rp {{number_format($stats['tripay_today'],0,',','.')}}</div></div></div></div></div>
    <div class="card mt-4"><div class="card-body"><h2 class="h5">Pendapatan 6 bulan terakhir</h2>@php($maxRevenue=max(1,$months->max('total')))<div class="d-flex align-items-end gap-3" style="height:180px">@foreach($months as $month)<div class="flex-fill text-center d-flex flex-column justify-content-end h-100"><div class="small text-muted">Rp {{number_format($month['total'],0,',','.')}}</div><div class="bg-primary rounded-top mx-auto" style="height:{{max(3,($month['total']/$maxRevenue)*120)}}px;width:min(44px,80%)"></div><div class="small mt-2">{{$month['label']}}</div></div>@endforeach</div></div></div>
@endif
<div class="card mt-4"><div class="card-body"><h2 class="h5">Alur layanan</h2><p class="mb-0">Pelanggan → Invoice → Pembayaran → Aktivasi layanan → Notifikasi WhatsApp.</p></div></div>
<script>
(() => {
 const select=document.getElementById('traffic-router'),status=document.getElementById('traffic-status'),updated=document.getElementById('traffic-updated');
 const rxText=document.getElementById('traffic-rx'),txText=document.getElementById('traffic-tx'),rxLine=document.getElementById('traffic-rx-line'),txLine=document.getElementById('traffic-tx-line');
 const history=new Map();let busy=false;
 const fmt=bps=>bps>=1e9?(bps/1e9).toFixed(2)+' Gbps':bps>=1e6?(bps/1e6).toFixed(2)+' Mbps':bps>=1e3?(bps/1e3).toFixed(1)+' Kbps':Math.round(bps)+' bps';
 const draw=samples=>{const rx=samples.map(v=>v.rx),tx=samples.map(v=>v.tx),max=Math.max(1,...rx,...tx),x=i=>48+i*(840/Math.max(1,samples.length-1)),y=v=>200-v/max*178,path=a=>a.map((v,i)=>(i?'L':'M')+x(i).toFixed(1)+' '+y(v).toFixed(1)).join(' ');rxLine.setAttribute('d',path(rx));txLine.setAttribute('d',path(tx));document.getElementById('traffic-scale').textContent=fmt(max);rxText.textContent=fmt(rx.at(-1));txText.textContent=fmt(tx.at(-1));};
 const poll=async()=>{if(busy)return;busy=true;try{const response=await fetch(@json(route('dashboard.traffic')),{headers:{'Accept':'application/json'},cache:'no-store'});if(!response.ok)throw new Error('HTTP '+response.status);const data=await response.json(),routers=data.routers||[],previous=select.value;if(!select.options.length){routers.forEach(r=>{const option=document.createElement('option');option.value=r.router_id;option.textContent=r.router+' — '+(r.interface||'interface belum diatur');select.append(option);});if(previous)select.value=previous;}const active=routers.find(r=>String(r.router_id)===String(select.value))||routers[0];if(!active){status.textContent='Belum ada router aktif.';return;}if(!select.value)select.value=active.router_id;if(active.ok){let samples=history.get(String(active.router_id))||[];samples.push({rx:active.rx_bps,tx:active.tx_bps});samples=samples.slice(-30);history.set(String(active.router_id),samples);draw(samples);updated.textContent='Diperbarui '+new Date(data.sampled_at).toLocaleTimeString();status.textContent='Interface '+active.interface;}else status.textContent='Gagal membaca interface '+(active.interface||'router')+'. Periksa interface dan koneksi API.';}catch(error){status.textContent='Gagal memuat trafik: '+error.message;}finally{busy=false;}};
 select.addEventListener('change',()=>{const samples=history.get(String(select.value));if(samples?.length)draw(samples);poll();});poll();setInterval(poll,30000);
})();
</script>
@endsection
