@extends('layouts.app')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-3 flex-wrap gap-2"><h1>Pelanggan</h1><div class="d-flex gap-2 flex-wrap">
@if(in_array($billingUser?->role,['super_admin','admin','finance'],true))<a class="btn btn-outline-success" href="{{route('customers.export',request()->query())}}">Export XLSX</a>@endif
@if(in_array($billingUser?->role,['super_admin','admin'],true))<form method="POST" action="{{route('customers.import')}}" enctype="multipart/form-data">@csrf<input type="file" name="file" accept=".xlsx,.xls,.csv" class="form-control form-control-sm" onchange="this.form.submit()" aria-label="Import XLSX atau CSV"></form>@endif
@if(in_array($billingUser?->role,['super_admin','admin','operator'],true))<a class="btn btn-primary" href="{{route('customers.create')}}">+ Tambah</a>@endif
</div></div>
<form class="row g-2 mb-3" method="GET" action="{{route('customers.index')}}">
    <div class="col-lg-4 col-md-6"><input name="search" type="search" maxlength="120" class="form-control" placeholder="Nama / ID / username / WhatsApp" value="{{request('search')}}" aria-label="Cari pelanggan"></div>
    <div class="col-lg-2 col-md-3"><select name="service_type" class="form-select" aria-label="Jenis layanan"><option value="">Semua layanan</option><option value="pppoe" @selected(request('service_type')==='pppoe')>PPPoE</option><option value="hotspot" @selected(request('service_type')==='hotspot')>Hotspot</option></select></div>
    <div class="col-lg-2 col-md-3"><select name="status" class="form-select" aria-label="Status pelanggan"><option value="">Semua status</option>@foreach(['active','isolated','suspended','terminated','trial'] as $s)<option value="{{$s}}" @selected(request('status')===$s)>{{$s}}</option>@endforeach</select></div>
    <div class="col-lg-2 col-md-4"><select name="package_id" class="form-select" aria-label="Paket"><option value="">Semua paket</option>@foreach($packages as $package)<option value="{{$package->id}}" @selected((string)request('package_id')===(string)$package->id)>{{$package->name}}</option>@endforeach</select></div>
    <div class="col-lg-2 col-md-4 d-flex gap-2"><button class="btn btn-outline-primary flex-grow-1">Filter</button><a class="btn btn-outline-secondary" href="{{route('customers.index')}}">Reset</a></div>
</form>
<div class="table-responsive shadow-sm"><table class="table table-sm table-hover mb-0"><thead><tr><th>ID</th><th>Nama</th><th>WA</th><th>Paket</th><th>PPPoE</th><th>Router</th><th>Status</th><th></th></tr></thead><tbody>@forelse($customers as $c)<tr><td>{{$c->customer_code}}</td><td>{{$c->name}}</td><td>{{$c->whatsapp_number?:$c->phone}}</td><td>{{$c->package?->name}}</td><td>{{$c->pppoe_username}}</td><td>{{$c->router?->name}}</td><td><span class="badge text-bg-{{ $c->status==='active'?'success':($c->status==='isolated'?'danger':'secondary')}}">{{$c->status}}</span></td><td>@if(in_array($billingUser?->role,['super_admin','admin','operator'],true))<a href="{{route('customers.edit',$c)}}" class="btn btn-sm btn-outline-secondary">Edit</a>@endif</td></tr>@empty<tr><td colspan="8" class="text-center p-4">Belum ada pelanggan.</td></tr>@endforelse</tbody></table></div><div class="mt-3">{{$customers->links()}}</div>
@endsection
