@extends('layouts.app')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-3 flex-wrap gap-2"><h1>Pelanggan</h1><div class="d-flex gap-2 flex-wrap">
@if(in_array($billingUser?->role,['super_admin','admin','finance'],true))<a class="btn btn-outline-success" href="{{route('customers.export')}}">Export XLSX</a>@endif
@if(in_array($billingUser?->role,['super_admin','admin'],true))<form method="POST" action="{{route('customers.import')}}" enctype="multipart/form-data">@csrf<input type="file" name="file" accept=".xlsx,.xls,.csv" class="form-control form-control-sm" onchange="this.form.submit()" aria-label="Import XLSX atau CSV"></form>@endif
@if(in_array($billingUser?->role,['super_admin','admin','operator'],true))<a class="btn btn-primary" href="{{route('customers.create')}}">+ Tambah</a>@endif
</div></div>
<form class="row g-2 mb-3"><div class="col-md-6"><input name="search" class="form-control" placeholder="Nama / ID / username" value="{{request('search')}}"></div><div class="col-md-2"><select name="status" class="form-select"><option value="">Semua status</option>@foreach(['active','isolated','suspended','terminated','trial'] as $s)<option value="{{$s}}" @selected(request('status')===$s)>{{$s}}</option>@endforeach</select></div><div class="col-md-2"><button class="btn btn-outline-primary w-100">Filter</button></div></form>
<div class="table-responsive shadow-sm"><table class="table table-sm table-hover mb-0"><thead><tr><th>ID</th><th>Nama</th><th>WA</th><th>Paket</th><th>PPPoE</th><th>Router</th><th>Status</th><th></th></tr></thead><tbody>@forelse($customers as $c)<tr><td>{{$c->customer_code}}</td><td>{{$c->name}}</td><td>{{$c->whatsapp_number?:$c->phone}}</td><td>{{$c->package?->name}}</td><td>{{$c->pppoe_username}}</td><td>{{$c->router?->name}}</td><td><span class="badge text-bg-{{ $c->status==='active'?'success':($c->status==='isolated'?'danger':'secondary')}}">{{$c->status}}</span></td><td>@if(in_array($billingUser?->role,['super_admin','admin','operator'],true))<a href="{{route('customers.edit',$c)}}" class="btn btn-sm btn-outline-secondary">Edit</a>@endif</td></tr>@empty<tr><td colspan="8" class="text-center p-4">Belum ada pelanggan.</td></tr>@endforelse</tbody></table></div><div class="mt-3">{{$customers->links()}}</div>
@endsection
