<?php
namespace App\Http\Controllers;
use App\Models\{Customer,Package,Router}; use App\Support\Audit; use Illuminate\Http\Request; use Illuminate\Validation\Rule;
class CustomerController extends Controller {
  public function index(Request $r){$q=Customer::with(['package','router'])->when($r->search,fn($x,$v)=>$x->where(fn($q)=>$q->where('name','like','%'.$v.'%')->orWhere('customer_code','like','%'.$v.'%')->orWhere('pppoe_username','like','%'.$v.'%')))->when($r->status,fn($x,$v)=>$x->where('status',$v))->latest()->paginate(25)->withQueryString();return view('customers.index',['customers'=>$q]);}
  public function create(){return view('customers.form',['customer'=>new Customer,'packages'=>Package::orderBy('name')->get(),'routers'=>Router::orderBy('name')->get()]);}
  public function store(Request $r){$data=$this->validated($r);$c=Customer::create($data);$c->pppoe_profile_normal=$c->pppoe_profile_normal?:$c->package?->normal_profile;$c->save();Audit::log('customer.created',Customer::class,$c->id,['code'=>$c->customer_code]);return redirect()->route('customers.index')->with('success','Pelanggan ditambahkan.');}
  public function edit(Customer $customer){return view('customers.form',['customer'=>$customer,'packages'=>Package::orderBy('name')->get(),'routers'=>Router::orderBy('name')->get()]);}
  public function update(Request $r,Customer $customer){$data=$this->validated($r,$customer);foreach(['pppoe_password','hotspot_password','portal_password'] as $secret){if(blank($data[$secret]??null))unset($data[$secret]);}$customer->update($data);if(!$customer->pppoe_profile_normal)$customer->update(['pppoe_profile_normal'=>$customer->package?->normal_profile]);Audit::log('customer.updated',Customer::class,$customer->id);return redirect()->route('customers.index')->with('success','Pelanggan diperbarui.');}
  private function validated(Request $r,?Customer $c=null):array{return $r->validate(['customer_code'=>['required','max:50',Rule::unique('customers','customer_code')->ignore($c?->id)],'name'=>'required|max:120','phone'=>'nullable|max:30','email'=>'nullable|email','address'=>'nullable','rt'=>'nullable|max:10','rw'=>'nullable|max:10','village'=>'nullable|max:120','district'=>'nullable|max:120','city'=>'nullable|max:120','latitude'=>'nullable|numeric|between:-90,90','longitude'=>'nullable|numeric|between:-180,180','ktp_number'=>'nullable|max:50','service_type'=>'required|in:pppoe,hotspot','status'=>'required|in:active,isolated,suspended,terminated,trial','due_day'=>'required|integer|min:1|max:28','grace_days'=>'nullable|integer|min:0|max:31','router_id'=>'nullable|exists:routers,id','package_id'=>'nullable|exists:packages,id','pppoe_username'=>['nullable','max:120',Rule::unique('customers','pppoe_username')->ignore($c?->id)],'pppoe_password'=>'nullable|string|max:255','pppoe_ip'=>'nullable|ip','pppoe_mac'=>'nullable|mac_address','pppoe_profile_normal'=>'nullable|max:120','pppoe_profile_isolir'=>'nullable|max:120','hotspot_username'=>['nullable','max:120',Rule::unique('customers','hotspot_username')->ignore($c?->id)],'hotspot_password'=>'nullable|string|max:255','olt_id'=>'nullable|exists:olts,id','olt_name'=>'nullable|max:120','pon_port'=>'nullable|max:50','onu_id'=>'nullable|max:50','onu_sn'=>'nullable|max:100','fup_enabled'=>'nullable|boolean','fup_limit_bytes'=>'nullable|integer|min:0','fup_speed_after'=>'nullable|max:50','is_auto_isolate'=>'nullable|boolean','portal_password'=>'nullable|string|min:8|max:255']);}
}
