@extends('layouts.app')
@section('content')
<div class="d-flex justify-content-between align-items-start flex-wrap gap-3"><div><h1>{{$invoice->invoice_number}}</h1><p>{{$invoice->customer->name}} — {{$invoice->period}}</p></div><div>@if($invoice->status==='unpaid' && $paymentChannels)<form method="POST" action="{{route('invoices.pay',$invoice)}}" class="d-flex gap-2">@csrf<select name="method" class="form-select" required>@foreach($paymentChannels as $channel)<option value="{{$channel['code']}}">{{$channel['name']}}</option>@endforeach</select><button class="btn btn-success">Buat Pembayaran</button></form>@elseif($invoice->status==='paid')<span class="badge text-bg-success fs-6">LUNAS</span>@endif</div></div>
<div class="card card-body mt-3"><p>Link pelanggan: <a href="{{route('public.pay',$invoice->public_token)}}" target="_blank" rel="noopener">{{route('public.pay',$invoice->public_token)}}</a></p><div class="row"><div class="col-md-6">Paket: <strong>{{$invoice->customer->package?->name}}</strong><br>Jatuh tempo: <strong>{{$invoice->due_date->format('d-m-Y')}}</strong></div><div class="col-md-6 text-md-end">Status: <strong>{{strtoupper($invoice->status)}}</strong></div></div>
<div class="table-responsive mt-3"><table class="table table-sm mb-0"><thead><tr><th>Rincian</th><th class="text-end">Jumlah</th></tr></thead><tbody>@foreach($invoice->items as $item)<tr><td>{{$item->description}} ({{$item->quantity}} × Rp {{number_format($item->unit_price,0,',','.')}})</td><td class="text-end">Rp {{number_format($item->line_total,0,',','.')}}</td></tr>@endforeach<tr><td>Subtotal</td><td class="text-end">Rp {{number_format($invoice->subtotal,0,',','.')}}</td></tr>@if($invoice->discount)<tr><td>Diskon</td><td class="text-end">− Rp {{number_format($invoice->discount,0,',','.')}}</td></tr>@endif @if($invoice->penalty)<tr><td>Denda</td><td class="text-end">Rp {{number_format($invoice->penalty,0,',','.')}}</td></tr>@endif @if($invoice->tax_amount)<tr><td>Pajak ({{$invoice->tax_rate}}%)</td><td class="text-end">Rp {{number_format($invoice->tax_amount,0,',','.')}}</td></tr>@endif</tbody><tfoot><tr><th>Total tagihan</th><th class="text-end fs-5">Rp {{number_format($invoice->total,0,',','.')}}</th></tr></tfoot></table></div>
@if($invoice->payment_url)<hr><a href="{{$invoice->payment_url}}" target="_blank" rel="noopener" class="btn btn-outline-primary">Buka Halaman Pembayaran</a>@endif</div>
@if($invoice->status==='unpaid')<div class="card mt-3"><div class="card-body"><h5>Pembayaran Manual</h5><form method="POST" action="{{route('invoices.manual-payment',$invoice)}}" class="row g-2">@csrf<div class="col-md-4"><label class="form-label">Nominal</label><input type="number" name="amount" class="form-control" value="{{$invoice->total}}" min="1" required></div><div class="col-md-4"><label class="form-label">Kanal pembayaran</label><input name="channel" class="form-control" value="Cash" maxlength="50" required></div><div class="col-md-4 d-flex align-items-end"><button class="btn btn-warning w-100">Catat Lunas Manual</button></div></form></div></div>@endif
@if($invoice->status==='unpaid')<div class="card mt-3"><div class="card-body"><h5>Penyesuaian Invoice</h5>@if($invoice->payments->contains('provider','tripay'))<div class="text-muted">Penyesuaian dikunci setelah checkout Tripay dibuat untuk mencegah nominal transaksi berbeda dengan invoice.</div>@else<form method="POST" action="{{route('invoices.adjust',$invoice)}}" class="row g-2">@csrf @method('PUT')<div class="col-md-4"><label class="form-label">Diskon (Rp)</label><input name="discount" type="number" min="0" max="{{$invoice->subtotal}}" value="{{$invoice->discount}}" class="form-control" required></div><div class="col-md-4"><label class="form-label">Denda (Rp)</label><input name="penalty" type="number" min="0" value="{{$invoice->penalty}}" class="form-control" required></div><div class="col-md-4 d-flex align-items-end"><button class="btn btn-outline-warning w-100">Simpan Penyesuaian</button></div><div class="form-text">Total dihitung ulang dari subtotal − diskon + pajak + denda.</div></form>@endif</div></div>@endif
<div class="card mt-3"><div class="card-body"><h5>Riwayat Pembayaran</h5><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Reference</th><th>Channel</th><th>Status</th><th>Waktu</th></tr></thead><tbody>@forelse($invoice->payments as $payment)<tr><td>{{$payment->reference ?? '—'}}</td><td>{{$payment->channel}}</td><td>{{$payment->status}}</td><td>{{$payment->paid_at}}</td></tr>@empty<tr><td colspan="4">Belum ada transaksi.</td></tr>@endforelse</tbody></table></div></div></div>
@endsection
